FROM postgres:17.2

# envsubst 설치
RUN apt-get update && apt-get install -y gettext-base && rm -rf /var/lib/apt/lists/*

# 기본 entrypoint에서 환경 변수 처리
ENTRYPOINT ["/bin/bash", "-c", "source /app/.env && exec docker-entrypoint.sh"]

# PostgreSQL 기본 포트
EXPOSE 5432
