FROM postgres:17.2

# envsubst 설치
RUN apt-get update && apt-get install -y gettext-base && rm -rf /var/lib/apt/lists/*

# 기본 entrypoint 유지
ENTRYPOINT ["docker-entrypoint.sh"]

# PostgreSQL 기본 포트
EXPOSE 5432
